### ISSUE TITLE
TURN THIS OFFFFFFF please

### ISSUE THREAD

**Issue by Industrial** [notwaldorf/cat-push-notifications#6]
This app since I pressed the on switch has been bugging me for two weeks with cat haiku's.

Please tell me how to turn this off. PLEASE NO MORE CATS.

I hate notifications too now. > : (

**Comment by Industrial** [comment]
When I flip the switch to off (By the way it doesnt say BLUE or WHITE is ON or OFF so i have no clue which is which) it doesnt stop.

**Comment by notwaldorf** [comment]
Eeeek sorry about that! Flipping the switch should have stopped the notifications, however, you can also go the nuclear route and block notifications at the site level. 

If you go to https://caturday-post.herokuapp.com/ and click on the green lock icon, you'll get a popup that looks like this:
<img width="362" alt="screen shot 2015-09-07 at 10 50 28 am" src="https://cloud.githubusercontent.com/assets/1369170/9721389/88328256-554e-11e5-9fbe-12f5a9f9bb34.png">

Choose "always block on this site".

**Comment by Industrial** [comment]
Thank you so much ^^
